[workspace]
members = ["firesql_core", "firesql-cli"]
resolver = "2"

[workspace.dependencies]
clap = { version = "4.5", features = ["derive"] }
firestore = "0.43.1"
tokio = { version = "1" }
futures = "0.3.31"
