[package]
name = "firesql_core"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.6"
pest_derive = "2.6"
serde_json = { version = "*", features = ["std"] }
firestore.workspace = true
futures.workspace = true
gcloud-sdk.workspace = true
itertools.workspace = true
